#!/usr/bin/env groovy

######################################################################
# Author:      Lakshman Brodie
# Date:        1st September 2021
# Description: Jenkins file
#
######################################################################

# Jenkinsfile (Declarative Pipeline)

pipeline {
    agent any 
    stages {
        stage('Build') {
            steps {
                echo 'Building...' 
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...' 
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying...' 
            }
        }
    }
}
