#!/usr/bin/env groovy
/*********************************************************************
 Author:      Lakshman Brodie
 Date:        1st September 2021
 Description: Jenkinsfile (Declartive Pipeline)
              I have C:\cygwin64\bin in my windows PATH so I can use UNIX
              commands.  I have deliberately not writted a shell script to
              do the build as the whole purpose of this exercise is to write
              a groovy script.
*********************************************************************/

pipeline {
    agent any
    
    environment {
        AWS_ACCESS_KEY_ID     = credentials('Jenkins-aws-secret-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('jenkins-aws-secret-access-key')
        BASE_DIR = 'C:/cygwin64/home/lab1301/src/lab1301-git/src'
    }
    
    stages {
        
        stage('Build') {
            
            steps {
                echo "========  The Workspace directory is ${WORKSPACE}"
                echo "========  The BASE_DIR  directory is ${BASE_DIR}"

                dir("${BASE_DIR}/Eclipse/Java/zooSimulation") {
                    /*
                     * This block will either build on WINDOWS or Cygwin.
                     * My Java code is developed in Eclipse under Windows 10
                    */
                    sh "pwd"
                    sh "mvn clean package"
                    sh "mvn compile"
                    sh "mvn package"
                }

                dir("${BASE_DIR}/Eclipse/Java/polymorphism") {
                    /*
                     * This block will either build on WINDOWS or Cygwin.
                     * My Java code is developed in Eclipse under Windows 10
                    */
                    sh "pwd"
                    sh "mvn clean package"
                    sh "mvn compile"
                    sh "mvn package"
                }

                dir("${BASE_DIR}/C++/polymorphism") {
                    /*
                     *  This block will only build on Cygwin as my C++ code is
                     *  developed under UNIX/Cygwin using vi
                    */
                    sh "pwd"
                    sh "make clean"
                    sh "make polymorphism"
                }

                dir("${BASE_DIR}/C++/zooPolymorphism") {
                    /*
                     *  This block will only build on Cygwin as my C++ code is
                     *  developed under UNIX/Cygwin using vi
                    */
                    sh "pwd"
                    sh "make clean"
                    sh "make zoo"  // naming convention of src file is out of step with directory name!
                }

                dir("${BASE_DIR}/C++/zooVisitorPattern") {
                    /*
                     *  This block will only build on Cygwin as my C++ code is
                     *  developed under UNIX/Cygwin using vi
                    */
                    sh "pwd"
                    sh "make clean"
                    sh "make zooVisitor"
                }
            }
        }

        stage('Test') {
            
            environment {
                JDIR = 'C:/cygwin64/home/lab1301/src/Eclipse/Java'
            }
            
            steps {
                echo 'Testing...'
                powershell 'Write-Output "cd /home/lab1301/src/lab1301-git/src/C++//zooVisitorPattern"'
                powershell 'Write-Output "./zooVisitor.exe"'
                
                dir("${BASE_DIR}/C++/zooVisitorPattern") {
                    /*
                     *  This block will only run on Cygwin as my C++ code is
                     *  developed under UNIX/Cygwin using vi
                    */
                    sh "pwd"
                    sh "ls -al"
                    sh "./zooVisitor.exe"
                }
                
                dir("${BASE_DIR}/C++/zooPolymorphism") {
                    /*
                     *  This block will only run on Cygwin as my C++ code is
                     *  developed under UNIX/Cygwin using vi
                    */
                    sh "pwd"
                    sh "ls -al"
                    sh "./zoo.exe"
                }
                
                dir("${BASE_DIR}/C++/polymorphism") {
                    /*
                     *  This block will only run on Cygwin as my C++ code is
                     *  developed under UNIX/Cygwin using vi
                    */
                    sh "pwd"
                    sh "ls -al"
                    sh "./polymorphism.exe"
                }
                
                dir("${BASE_DIR}/Scripts/Python/polymorphism") {
                    sh "pwd"
                    sh "ls -al"
                    sh "python3 ./polymorphism.py"
                }
                
                dir("${BASE_DIR}/Scripts/Python/zoo") {
                    sh "pwd"
                    sh "ls -al"
                    sh "python3 ./zoo.py"
                }
                
                dir("${BASE_DIR}/Eclipse/Java/zooSimulation") {
                    sh "pwd"
                    sh "ls -al"
                    sh 'javaw.exe -p "${JDIR}/zooSimulation/target/classes" -m zooSimulation/zoo.zoo'
                }
                
                dir("${BASE_DIR}/Eclipse/Java/polymorphism") {
                    sh "pwd"
                    sh "ls -al"
                    sh 'javaw.exe -p "${JDIR}/polymorphism/target/classes" -XX:+ShowCodeDetailsInExceptionMessages -m Polymorphisim/polymorphismExamples.polymorphism'
                }
            }
        }
        
        stage('Deploy') {
            /*
             *  To deploy to AWS, from the AWS Management Console overview page:
             *   1) Enable Elastic Beanstalk (EB) service
              *  2) Select the S3 service under storage option
              *  Both the above are chargeable services so keep an eye on AWS resources via links below:
              *        https://us-east-2.console.aws.amazon.com/ec2/v2/home?region=us-east-2#Home:
              *        https://console.aws.amazon.com/cost-management/home?region=us-east-2#/dashboard
              *  Disable "Free-Tier" services that areincurring charges via link below:
              *        https://console.aws.amazon.com/billing/home#/freetier
              *  Cancel services identified above via link below:
              *        https://us-west-2.console.aws.amazon.com/ec2
              
              *  I have stopped all services and terminated my AWS instance as I've incurred
              *  charges from the above two services.  The only resources that I'm now using are 1 key pair and 
              *  8 Security Groups.
             */
            
            environment {
                LBIN = 'C:/cygwin64/home/lab1301/.local/bin'
            }
            
            steps {
                echo 'Deploying...'
                sh "${LBIN}/aws --version"
                //sh "${LBIN}/aws configure set region us-east-2"
                //sh "${LBIN}/aws s3 cp <list of files to be copies to AWS instance...."
                
                //sh "${LBIN}/aws ec2 describe-instance-attribute --instance-id   i-0934d5d085832524e --attribute userData"
                //sh "${LBIN}/aws  ec2 describe-availability-zones --output table"
            }
        }
    }
}

